version: '3'

services:
  
  foodlane-couchdb:
    image: couchdb:latest
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: my_admin_password
    ports: 
      - 5984:5984

  foodlane-server:
    build: ./app
    volumes:
      - ./app:/opt/app
    ports:
      - 3000:3000
    depends_on:
      - foodlane-couchdb

  foodlane-test:
    build: ./app
    volumes:
      - ./app:/opt/app
    ports:
      - 3001:3001
    depends_on:
      - foodlane-server
    command: ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- --recursive
